"""Generate on-device assets for the ESP32 sketch:
  - firmware/esp32_llm/vocab.h : token id -> raw UTF-8 bytes, so the device just
    Serial.write()s the bytes of each generated token (llama2.c style).
  - prints the prompt token ids for a fixed demo prompt to paste into the sketch.
"""

import argparse
import os

from tokenizers import Tokenizer

HERE = os.path.dirname(os.path.abspath(__file__))
PROMPT = "Once upon a time"


def bytes_to_unicode():
    """GPT-2 byte-level alphabet: raw byte -> a printable codepoint.

    Same function HuggingFace's ByteLevel pre-tokenizer uses. We only need it here,
    on the host: the C side gets a precomputed byte -> token-id table, so it never
    has to touch Unicode at all.
    """
    bs = (list(range(ord("!"), ord("~") + 1))
          + list(range(ord("\xa1"), ord("\xac") + 1))
          + list(range(ord("\xae"), ord("\xff") + 1)))
    cs, n = bs[:], 0
    for b in range(256):
        if b not in bs:
            bs.append(b)
            cs.append(256 + n)
            n += 1
    return {b: chr(c) for b, c in zip(bs, cs)}


def write_encoder_tables(f, tok_path):
    """Emit the two tables a C BPE encoder needs.

      BYTE_TOK[256]   raw byte -> id of its single-character byte-level piece.
                      Every byte is in the initial alphabet, so this never misses
                      and the device needs no UTF-8 handling.
      MERGE_A/B/C[]   merge rules in RANK ORDER (index = rank). Applying the
                      lowest-rank applicable pair repeatedly reproduces exactly
                      what tokenizers does.

    Storing merges as *ids* rather than strings means the C side compares ints.
    """
    import json

    d = json.load(open(tok_path))
    vocab = d["model"]["vocab"]
    merges = d["model"]["merges"]

    b2u = bytes_to_unicode()
    byte_tok = []
    for b in range(256):
        piece = b2u[b]
        if piece not in vocab:
            raise SystemExit(f"byte {b} -> {piece!r} không có trong vocab; "
                             "tokenizer không phải ByteLevel BPE?")
        byte_tok.append(vocab[piece])

    ma, mb, mc = [], [], []
    for m in merges:
        a, b = (m if isinstance(m, list) else m.split(" ", 1))
        merged = a + b
        if a not in vocab or b not in vocab or merged not in vocab:
            continue  # merge tạo ra token bị cắt khỏi vocab -- bỏ qua
        ma.append(vocab[a]); mb.append(vocab[b]); mc.append(vocab[merged])

    def arr(name, xs):
        f.write(f"static const int {name}[{len(xs)}] = {{\n")
        for i in range(0, len(xs), 20):
            f.write("  " + ",".join(str(x) for x in xs[i:i + 20]) + ",\n")
        f.write("};\n")

    f.write("\n// ---- encode tables (src/gen_assets.py --encoder) ----\n")
    arr("BYTE_TOK", byte_tok)
    f.write(f"#define N_MERGES {len(ma)}\n")
    arr("MERGE_A", ma)
    arr("MERGE_B", mb)
    arr("MERGE_C", mc)
    print(f"  encode tables: 256 byte entries, {len(ma)} merges")


def main():
    # Defaults reproduce the original ESP32 behaviour exactly; the flags exist so
    # the same asset can be built for another vocab / another runtime target
    # (firmware/jetson uses --vocab 4096).
    ap = argparse.ArgumentParser()
    ap.add_argument("--vocab", type=int, default=32768)
    ap.add_argument("--out", default=None)
    ap.add_argument("--prompt", default=PROMPT)
    ap.add_argument("--encoder", action="store_true",
                    help="also emit BPE encode tables so the device can tokenize "
                         "typed input itself (firmware/jetson/generate_cuda.cu)")
    args = ap.parse_args()

    TOK = os.path.join(HERE, "..", "data", f"bpe{args.vocab}.json")
    OUT = args.out or os.path.join(HERE, "..", "firmware", "esp32_llm", "vocab.h")

    tok = Tokenizer.from_file(TOK)
    V = tok.get_vocab_size()

    # Raw bytes per token: decode single-id sequences. For the ASCII TinyStories
    # domain this reconstructs text exactly when pieces are concatenated.
    blob = bytearray()
    offs = [0]
    for i in range(V):
        s = tok.decode([i])
        blob.extend(s.encode("utf-8"))
        offs.append(len(blob))

    with open(OUT, "w") as f:
        f.write("// Generated by src/gen_assets.py -- token id -> raw UTF-8 bytes.\n")
        f.write("#ifndef VOCAB_H\n#define VOCAB_H\n")
        f.write(f"#define VOCAB_N {V}\n")
        f.write(f"static const unsigned char VOCAB_BLOB[{len(blob)}] = {{\n")
        for i in range(0, len(blob), 20):
            f.write("  " + ",".join(str(b) for b in blob[i:i+20]) + ",\n")
        f.write("};\n")
        f.write(f"static const int VOCAB_OFF[{len(offs)}] = {{\n")
        for i in range(0, len(offs), 20):
            f.write("  " + ",".join(str(o) for o in offs[i:i+20]) + ",\n")
        f.write("};\n")
        if args.encoder:
            write_encoder_tables(f, TOK)
        f.write("#endif\n")

    print(f"wrote {OUT}: {V} tokens, blob {len(blob)/1024:.0f} KB"
          + (" + encode tables" if args.encoder else ""))

    ids = tok.encode(args.prompt).ids
    print(f'prompt "{args.prompt}" -> {len(ids)} ids: {ids}')
    print(f"round-trip: {tok.decode(ids)!r}")
    print("\nPaste into the sketch:")
    print(f"static const int PROMPT_IDS[] = {{{', '.join(map(str, ids))}}};")


if __name__ == "__main__":
    main()
